version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: samitprsl/todo-app:frontend
    container_name: frontend-container
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: samitprsl/todo-app:backend
    container_name: backend-container
    ports:
      - "5000:5000"